- name: installed packages
  hosts: web
  become: yes
  tasks:
  - name: installed packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - { name: 'git' , state: 'present'}
    - { name: 'mysql' , state: 'present'}
    - { name: 'nginx' , state: 'absent'}
    - { name: 'gcc' , state: 'absent'}
    