- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - 03-vars.yaml
  tasks:
  - name: print the variables from files
    ansible.builtin.debug:
      msg: "COURSE IS {{COURSE}}, TRAINER IS {{TRAINER}}, DURATION IS {{DURATION}}"