- name: conditions
  hosts: local
  connection: local
  vars:
    my_number: 20
  tasks:
  - name: print if number is grater than 10
    ansible.builtin.debug:
      msg: "given number is {{my_number}} is grater than 10"
    when: my_number > 10

  - name: print if number is less than or equal to  10
    ansible.builtin.debug:
      msg: "given number is {{my_number}} is less than or equal to 10"
    when: my_number <= 10