- name: datatypes
  hosts: local
  connection: local
  vars:   
    course_name: "devops with aws"
    trainer_name: "siva kumar reddy"
    dyration: 120 
    topics:
    - linux
    - shell
    - ansible
    - docker
    - kubernate
    - jenkins
    live: true
    tools:
      ci: jenkins
      configuration: ansible
      cloud: aws
      containerization: docker
    tasks:
    - name: print the full information
      ansible.builtin.debug:
        msg: "hello iam learning {{course_name}}, trainer name is: {{trainer_name}}, duration: {{duration}}, topics are: {{topics}}, is it {{live}}, tools coverd are: {{tools}}"
   
