- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Srikanth')}}"


  - name: convert string to list
    vars:
      movies: "Devara,HIT,Court,Hi Nana"
    ansible.builtin.debug:
      msg: "movies are {{ movies | split(',')}}"