- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variables
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Srikanth')}}"

  # convert string to list
  - name: convert string to list
    vars:
      movies: "Devara,HIT,Court,Hi Nana"
    ansible.builtin.debug:
      msg: "movies are {{ movies | split(',')}}"


  # convert map to list items

  - name: convert map to list
    vars:
      course:
        name: ansible
        duration: 120hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course Info {{ course | dict2items}}"

  # convert list to map

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '120hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course Info {{ course | items2dict }}"

  - name: convert upper to lower
    vars:
      name: "STIKANTH BOMMISETTY"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"


  - name: convert lower to upper
    vars:
      name: "srikanth bommisetty"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: print min and max
    vars:
      numbers: [12,34,25,342,12,1342,26]
    ansible.builtin.debug:
      msg: "Min is: {{ numbers | min }}, Max is: {{ numbers | max }}"

  - name: check ip address is valid or not
    vars:
      ip: "244.253.267.245"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.addr }}"
    
    
    



  